'use strict';
angular.module('Nuchatapp.controllers', [])
.controller('LoginCtrl', LoginCtrl)
.controller('RegisterCtrl', RegisterCtrl)
.controller('AccountCtrl', AccountCtrl)
.controller('RoomCtrl', RoomCtrl)
.controller('ChatCtrl', ChatCtrl)
.controller('FriendCtrl', FriendCtrl)
.controller('DirectoryCtrl', DirectoryCtrl)
.controller('DirArticleCtrl', DirArticleCtrl)
.controller('DirFilesCtrl', DirFilesCtrl)
.controller('DirLinksCtrl', DirLinksCtrl)
.controller('DirCalendarCtrl', DirCalendarCtrl)
.controller('VideoCallCtrl', VideoCallCtrl);
